USE `Autokolcsonzo`;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Szemelyauto`;
DROP TABLE IF EXISTS `Kisteherauto`;
DROP TABLE IF EXISTS `Kolcsonzo`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS `Kolcsonzo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nev` VARCHAR(60) NOT NULL,
  `Cim` VARCHAR(60) NOT NULL,
  `Tulajdonos` VARCHAR(60) NOT NULL,
  CONSTRAINT `Id_PK` PRIMARY KEY (`Id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Szemelyauto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Rendszam` VARCHAR(7) NOT NULL,
  `Marka` VARCHAR(20) NOT NULL,
  `Jarmutipus` VARCHAR(20) NOT NULL,
  `Foglalt` BOOLEAN, NOT NULL,
  `Szemelyautotipus` VARCHAR(5) NOT NULL,
  `MaxSzemely` INT NOT NULL,
  `KolcsonzoId` INT NOT NULL,
  CONSTRAINT `Id_PK` PRIMARY KEY (`Id`)
  CONSTRAINT `Kolcsonzo_Id_FK`
    FOREIGN KEY (`KolcsonzoId`) REFERENCES `Kolcsonzo`(`Id`)
      ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Kisteherauto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Rendszam` VARCHAR(7) NOT NULL,
  `Marka` VARCHAR(20) NOT NULL,
  `Jarmutipus` VARCHAR(20) NOT NULL,
  `Foglalt` BOOLEAN, NOT NULL,
  `MaxTeher` INT NOT NULL,
  `KolcsonzoId` INT NOT NULL,
  CONSTRAINT `Id_PK` PRIMARY KEY (`Id`)
  CONSTRAINT `Kolcsonzo_Id_FK`
    FOREIGN KEY (`KolcsonzoId`) REFERENCES `Kolcsonzo`(`Id`)
      ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;
