USE `Konyvtarak`;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Konyvmoly`;
DROP TABLE IF EXISTS `KonyvKategoria`;
DROP TABLE IF EXISTS `Varosok`;
DROP TABLE IF EXISTS `Konyv`;
DROP TABLE IF EXISTS `Konyvtar`;
DROP TABLE IF EXISTS `KonyvtarKonyvei`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS `Konyvmoly` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nev` VARCHAR(60) NOT NULL,
  CONSTRAINT `Konyvmoly_PK` PRIMARY KEY (`Id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `KonyvKategoria` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `KategoriaNev` VARCHAR(30) NOT NULL,
  CONSTRAINT `KonyvKategoria_PK` PRIMARY KEY (`Id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Varosok` (
  `Irsz` SMALLINT NOT NULL,
  `VarosNev` VARCHAR(30) NOT NULL,
  CONSTRAINT `Varosok_PK` PRIMARY KEY (`Irsz`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Konyv` (
  `ISBN` VARCHAR(20) NOT NULL,
  `Szerzo` VARCHAR(60) NOT NULL,
  `Cim` VARCHAR(60) NOT NULL,
  `KategoriaId` INT NOT NULL,
  CONSTRAINT `Konyv_PK` PRIMARY KEY (`ISBN`),
  CONSTRAINT `Konyv_KonyvKategoria_FK`
    FOREIGN KEY (`KategoriaId`) REFERENCES `KonyvKategoria`(`Id`)
      ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Konyvtar` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Tulajdonos` VARCHAR(60) NOT NULL,
  `Irsz` SMALLINT NOT NULL,
  `Utca` VARCHAR(60) NOT NULL,
  `HSZ` SMALLINT NOT NULL,
  CONSTRAINT `Konyvtar_PK` PRIMARY KEY (`Id`),
  CONSTRAINT `Konyvtar_Varosok_FK`
    FOREIGN KEY (`Irsz`) REFERENCES `Varosok`(`Irsz`)
      ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `KonyvtarKonyvei` (
  `ISBN` VARCHAR(20) NOT NULL,
  `KonyvtarId` INT NOT NULL,
  `Db` INT DEFAULT NULL,
  CONSTRAINT `KonyvtarKonyvei_PK` PRIMARY KEY (`ISBN`, `KonyvtarId`),
  CONSTRAINT `KonyvtarKonyvei_Konyv_FK`
    FOREIGN KEY (`ISBN`) REFERENCES `Konyv`(`ISBN`)
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT `KonyvtarKonyvei_Konyvtar_FK`
    FOREIGN KEY (`KonyvtarId`) REFERENCES `Konyvtar`(`Id`)
      ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;
