@baseUrl = http://localhost:5210


### Minden Customer lekérdezése
GET {{baseUrl}}/api/Customer
Content-Type: application/json
Accept: application/json

###

### új customer hozzáadása
POST {{baseUrl}}/api/Customer
Content-Type: application/json
Accept: application/json

{
  "email": "uj@pelda.hu"
}

###

### customer módosítása
PUT {{baseUrl}}/api/Customer/uj@pelda.hu
Content-Type: application/json
Accept: application/json

{
  "email": "modositott@pelda.hu"
}

###

### customer törlése
DELETE  {{baseUrl}}/api/Customer/modositott@pelda.hu
Accept: application/json

###

### már létező e-mail című customer hozzáadása
POST {{baseUrl}}/api/Customer
Content-Type: application/json
Accept: application/json

{
  "email": "a@b.cd"
}

###

### hibás e-mail című customer hozzáadása 1
POST {{baseUrl}}/api/Customer
Content-Type: application/json
Accept: application/json

{
  "email": "Hibás e-mail cím formátum"
}

###

### hibás e-mail című customer hozzáadása 2
POST {{baseUrl}}/api/Customer
Content-Type: application/json
Accept: application/json

{
  "email": "Az_e-mail_cím_maximum_50_karakter_hosszu_lehet@pelda.hu"
}

###

### hibás e-mail című customer hozzáadása 3
POST {{baseUrl}}/api/Customer
Content-Type: application/json
Accept: application/json

{
  "email": "Az_e-mail_cím_maximum_50_karakter_hosszu_lehet_es_meg_rossz_is"
}

###
