@baseUrl = https://localhost:7210
@token = valami

### Regisztráció - új user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "fullName": "Minta Mókus",
  "email": "minta@pelda.hu",
  "password": "Pelda123!"
}

###


### Login - seedelt admin user
POST {{baseUrl}}/api/Auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "admin@pelda.hu",
  "password": "Admin123"
}

###


### Saját user adatai - token kell
GET {{baseUrl}}/api/Auth/me
Authorization: Bearer {{token}}
Accept: application/json

###



### Összes ticket lekérdezése.      // Ez a ### a komment, blokk jelzés és egyben fejléc is a megjelenítésében. 
GET {{baseUrl}}/api/Tickets
Accept: application/json

###


### Összes kategoria lekérdezése.    
GET {{baseUrl}}/api/Categories
Accept: application/json

###

### Egy ticket lekérdezése:
GET {{baseUrl}}/api/Tickets/1
Accept: application/json

###

### Keresés szövegre
GET {{baseUrl}}/api/Tickets?
    searchTerm=bejelentkez
Accept: application/json

###

### Szűrés státusz szerint
GET {{baseUrl}}/api/Tickets?
    status=1
Accept: application/json

###

### Szűrés prioritás szerint
GET {{baseUrl}}/api/Tickets?
    priority=4
Accept: application/json

###

### Rendezés cím szerint növekvőben
GET {{baseUrl}}/api/Tickets?
    sortBy=title&
    sortDirection=asc
Accept: application/json

###

### Lapozás elso oldal 2 elemmel
GET {{baseUrl}}/api/Tickets?
    pageNumber=1&
    pageSize=2
Accept: application/json

###

### Lapozás 2. oldal 2 elemmel
GET {{baseUrl}}/api/Tickets?
    pageNumber=2&
    pageSize=2
Accept: application/json

###

### Összetett query
GET {{baseUrl}}/api/Tickets?
    searchTerm=a&
    status=1&
    sortBy=priority&
    sortDirection=desc&
    pageNumnber=1&
    pageSize=5
Accept: application/json

###

### Nemlétező lekérése
GET {{baseUrl}}/api/Tickets/999
Accept: application/json

###

### Új tiket létrehozása hibásan
POST {{baseUrl}}/api/Tickets
Content-Type: application/json
Accept: application/json

{
  "title": "Nyomtatási probléma",
  "description": "Nem tud a user nyomtatni.",
  "priority": 3
}

###

### Új tiket létrehozása jól
POST {{baseUrl}}/api/Tickets
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "title": "Nyomtatási probléma",
  "description": "Nem tud a user nyomtatni.",
  "priority": 3,
  "categoryId": 1
}

###

### Új tiket létrehozása - tűl rövid leírás
POST {{baseUrl}}/api/Tickets
Content-Type: application/json
Accept: application/json

{
  "title": "Nyomtatási probléma",
  "description": "Nem",
  "priority": 4,
  "categoryId": 1
}

###

### Új tiket létrehozása - tűl rövid title
POST {{baseUrl}}/api/Tickets
Content-Type: application/json
Accept: application/json

{
  "title": "s",
  "description": "Nem tud a user nyomtatni.",
  "priority": 4,
  "categoryId": 1
}

###


### Tiket módosítása
PUT {{baseUrl}}/api/Tickets/4
Content-Type: application/json
Accept: application/json

{
  "title": "Nyomtatási probléma",
  "description": "Nem tud a user nyomtatni.",
  "priority": 4,
  "categoryId": 1
}

###

### Tiket státusz módosítása jól
PUT {{baseUrl}}/api/Tickets/1
Content-Type: application/json
Accept: application/json

{
  "status": 2
}

###

### Tiket státusz módosítása hibás
PUT {{baseUrl}}/api/Tickets/1/Status
Content-Type: application/json
Accept: application/json

{
  "status": 4
}

###


### Tiket törlése
DELETE  {{baseUrl}}/api/Tickets/4
Accept: application/json

###




